### ISSUE TITLE
Feat: Filebrowser -> added to my deployment howto

### ISSUE THREAD

**Issue by daemon31337** [Viren070/docker-compose-vps-template#6]
Filebrowser - something I use as a simple method to upload and download files, it also automatically compresses large sets of files or directories. I find it useful to backup and move files to/from my personal system and servers at times. Adding so others may follow if they want to add this or other containers they may want to run (**caution:** if you dont know how this environment is setup by Viren, dont mod it until you do). Also putting here to add if you would like viren but you likely use scp command line:

1. create directory structure
ubuntu@daemonrealm:/opt/docker/apps$ mkdir filebrowser

in data too:
ubuntu@daemonrealm:/opt/docker/data$ mkdir filebrowser

2. create database file before starting the container or else it crash loops and creates a directory not a file on local system
ubuntu@daemonrealm:/opt/docker/data$ touch database.db

3. Navigate back to your /opt/docker/apps/filebrowser. Create compose.yaml then populate:
```
services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    restart: unless-stopped
    user: "${PUID}:${PGID}"
    expose:
      - "9090"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.filebrowser.rule=Host(`${FILEBROWSER_HOSTNAME?}`)"
      - "traefik.http.routers.filebrowser.entrypoints=websecure"
      - "traefik.http.routers.filebrowser.tls.certresolver=letsencrypt"
      - "traefik.http.services.filebrowser.loadbalancer.server.port=9090"
      - "traefik.http.routers.filebrowser.middlewares=authelia@docker"
    volumes:
      - "${DOCKER_DATA_DIR}/filebrowser/database.db:/database.db"
      - "${FILEBROWSER_HOME}:/srv"
    environment:
      - FB_ENCRYPTION_KEY=${FB_ENCRYPTION_KEY}
      - FB_PORT=9090
    profiles:
      - filebrowser
      - all
```
4. Then create .env and populate:
```
# Filebrowser is a simple lightweight web enable file management utility. Use 'openssl rand -base64 32' to generate the key.
# Set FILEBROWSER_HOME to the home files directory that filebrowser will use for all file storage and navigation on login. 
# This can be set to higher level directories at your own risk
# Remember to change the default admin:admin password on first login. This container is protected by Authelia 2FA as well.
FILEBROWSER_HOSTNAME=YOUR_FILEBROWSER_DOMAIN
FB_ENCRYPTION_KEY=
FILEBROWSER_HOME=/opt/docker/filebrowser/files

```
5. Navigate to /opt/docker/apps modify compose.yaml and add under include:

`- filebrowser/compose.yaml`

6. same location now finally add your profile to run in your profiles section in .env. I add and remove profiles as I configure them/need them up and running + the default one. You can remove the profiles: section in the compose above if you want to run it as default (which I will be doing).

```
# TL;DR, each folder in the apps directory is a profile.
# And additional profiles are as follows: stremio, indexers, debrid_media_server
# A final profile - all - is provided that includes every service in the template.
COMPOSE_PROFILES="speedtest-tracker, librespeed, aiostreams, warp, mediaflow-proxy, filebrowser"
```
7. last as I use Honey as my main dashboard - update it to include filebrowser. modify /opt/docker/data/honey/config.json

Under services add:
```
 {
			"name": "Filebrowser",
			"desc": "File management and explorer.",
			"href": "https:/YOUR_FILEBROWSER_DOMAIN",
			"icon": "https://raw.githubusercontent.com/filebrowser/filebrowser/refs/heads/master/frontend/public/img/icons/favicon.ico"
		},
```
8. Restart docker and you're all set, dont forget to change the default login
